## working directory 확인

In [13]:
%pwd

'C:\\Users\\LG\\Desktop\\보아즈20-1'

# module 모듈
module : 어떤 것의 일부분 또는 조각

* import 모듈명<br>
  import 모듈명 as 별명
  
  
* 모듈명.함수()


* from 모듈명 import 함수명1, 함수명2, 함수명3<br>
  from 모듈명 import *

In [1]:
import numpy

In [2]:
numpy.random.rand() # [0,1) 사이의 실수 난수 배열

0.9416013769984128

In [4]:
import numpy as np # 별칭 사용

In [5]:
np.random.rand()

0.8635022880055612

In [6]:
random.rand()

NameError: name 'random' is not defined

In [10]:
from numpy import random

In [12]:
random.rand()

0.45535350522025986

# Numpy
* Numerical Python 의 약어로 파이썬으로 고성능 수치 계산을 쉽고 빠르게 할 수 있도록 만든 패키지
* Numpy 홈페이지 : http://www.numpy.org
* 아나콘다 배포판에는 Numpy 가 포함되어 있음

In [172]:
import numpy as np

## 배열
* **순서가 있는 같은 종류(같은 데이터 타입)**의 데이터가 저장된 집합
* 많은 숫자 데이터를 하나의 변수에 넣고 관리할 때 사용
* 리스트와 유사하나 **리스트보다 작은 메모리**를 차지하며 **빠르게 데이터 처리**가 가능

파이썬은 자체적으로 배열 자료형을 제공하지 않음

다차원 데이터, 수치 데이터를 효과적으로 처리

### 리스트와의 차이점
* 배열은 **모든 원소가 같은 자료형** 이어야 함
* 배열의 **크기는 고정**되어있으며 생성 후 원소 개수를 바꿀 수 없음

### 1차원 배열

In [173]:
data1 = [0, 1, 2, 3, 4, 5] # list 데이터 타입
a1 = np.array(data1)
a1 # array형

array([0, 1, 2, 3, 4, 5])

In [174]:
data2 = [0.1, 5.4, 12, 0.5] # 정수 실수 혼합
a2 = np.array(data2)
a2 # 모두 실수형으로 변환 : 더 큰 사이즈의 datatype으로 변환

array([ 0.1,  5.4, 12. ,  0.5])

In [175]:
a1 = np.array(data1, dtype = float) # 타입변환
a1

array([0., 1., 2., 3., 4., 5.])

In [176]:
a1.dtype

dtype('float64')

#### 범위를 지정해서 배열 생성

In [178]:
a1 = np.arange(0, 10, 2) # range함수와 유사
a1

array([0, 2, 4, 6, 8])

In [179]:
a2 = np.arange(1, 10)
a2

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [180]:
a3 = np.arange(5)
a3

array([0, 1, 2, 3, 4])

#  

In [181]:
a = np.array([[1,2,3],[4,5,6],[7,8,9]])
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

### m x n 의 2 차원 배열 생성
.reshape(m,n)

_주의 : arange()로 생성한 배열의 원소 개수와 reshape(m,n) 의 m x n 의 개수가 같아야 함_

In [185]:
b1 = np.arange(12).reshape(4,3)
b1

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

#  

#### 범위의 시작과 끝, 데이터의 갯수를 지정해 배열 생성
# linspace(start, stop, num)
arange()와 달리 stop 값이 포함이 됨

In [186]:
arr1 = np.linspace(1, 10, 10); arr1

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [187]:
arr2 = np.linspace(0, np.pi, 12)
arr2

array([0.        , 0.28559933, 0.57119866, 0.856798  , 1.14239733,
       1.42799666, 1.71359599, 1.99919533, 2.28479466, 2.57039399,
       2.85599332, 3.14159265])

In [188]:
arr2.shape

(12,)

In [189]:
arr2.reshape(3,4)

array([[0.        , 0.28559933, 0.57119866, 0.856798  ],
       [1.14239733, 1.42799666, 1.71359599, 1.99919533],
       [2.28479466, 2.57039399, 2.85599332, 3.14159265]])

#   

### 통계를 위한 연산
sum(), mean(), std(), var(), min(), max(), cumsum(), cumprod() 등

In [182]:
arr3 = np.arange(1,6); arr3

array([1, 2, 3, 4, 5])

In [183]:
arr3.cumsum() # 누적합

array([ 1,  3,  6, 10, 15], dtype=int32)

In [184]:
arr3.cumprod() # 누적곱

array([  1,   2,   6,  24, 120], dtype=int32)

## 난수 배열 생성하기
low 가 생략되면 0, size 가 생략되면 1 개 난수 생성

`np.random.rand()` : [0,1) 사이의 **실수** 난수 배열

`np.random.randint()` : [low, high) 사이의 **정수** 난수 배열

In [198]:
np.random.seed(10)

In [199]:
r_num1 = np.random.rand()
r_num1

0.771320643266746

In [192]:
r_num2 = np.random.rand(2,3) # 배열의 형태 2*3
r_num2

array([[0.02075195, 0.63364823, 0.74880388],
       [0.49850701, 0.22479665, 0.19806286]])

In [200]:
np.random.randint(10, size = (3,4))

array([[4, 0, 1, 9],
       [0, 1, 8, 9],
       [0, 8, 6, 4]])

In [201]:
np.random.randint(1,30)

20

#   

# Pandas
* 데이터 분석과 처리를 쉽게 할 수 있게 도와주는 라이브러리( Python의 R화라고 생각하면 편리)
* pandas 홈페이지: http://pandas.pydata.org
* 아나콘다 배포판에 포함.

**라이브러리(library)란?**<br>
다른 프로그램의 구성 요소로 사용하기 위해 미리 만들어 둔 프로그램 조각이다. 즉, 자주 사용하는 기능을 모듈·패키지로 만들어 둔 것이다.

In [16]:
import pandas as pd

## 1 pandas의 자료구조
pandas는 기본적으로 정의되는 자료구조 Series와 DataFrame을 사용

### DataFrame
- 표(Table)와 같은 2차원 데이터를 처리
- index, columns

In [ ]:
pd.DataFrame()

In [17]:
# np.array 데이터
data_num = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
pd.DataFrame(data_num) # index와 column 자동생성

0  1  2
0  1  2  3
1  4  5  6
2  7  8  9

In [19]:
index_date = pd.date_range('2020-01-13', periods=3)
columns_list = ['A', 'B', 'C']

# 인덱스와 컬럼 지정
pd.DataFrame(data_num, index=index_date, columns=columns_list)

A  B  C
2020-01-13  1  2  3
2020-01-14  4  5  6
2020-01-15  7  8  9

In [36]:
# 딕셔너리 데이터
data_dic = {'id' : ['A23', 'C43', 'A23', 'A23', 'C43'],
            'year' : [2019, 2019, np.nan, 2020, 2020],
            'sales' : np.random.randint(0, 500, size = 5)}
data_dic 

{'id': ['A23', 'C43', 'A23', 'A23', 'C43'],
 'year': [2019, 2019, nan, 2020, 2020],
 'sales': array([467,  57, 131, 305, 162])}

In [76]:
df = pd.DataFrame(data_dic) # 간편~
df

id    year  sales
0  A23  2019.0    467
1  C43  2019.0     57
2  A23     NaN    131
3  A23  2020.0    305
4  C43  2020.0    162

In [54]:
# 컬럼 순서를 지정하고 할때
pd.DataFrame(data_dic, columns=['sales','id','year'])

sales   id    year
0    467  A23  2019.0
1     57  C43  2019.0
2    131  A23     NaN
3    305  A23  2020.0
4    162  C43  2020.0

In [70]:
# index 지정
pd.DataFrame(data_dic, index=['a','b','c','d','e'])

id    year  sales
a  A23  2019.0    467
b  C43  2019.0     57
c  A23     NaN    131
d  A23  2020.0    305
e  C43  2020.0    162

## 예제)
다음자료를 이용하여 데이터 프레임을 만들어주세요.

In [2]:
birds = ['갈매기','비둘기','까치','까마귀','가마우지','거위']

In [11]:
# import pandas as pd
# import numpy as np
num = np.arange(len(birds))
pd.DataFrame({'code':num, 'species':birds})

code species
0     0     갈매기
1     1     비둘기
2     2      까치
3     3     까마귀
4     4    가마우지
5     5      거위

#  

In [43]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 3 columns):
id       5 non-null object
year     4 non-null float64
sales    5 non-null int32
dtypes: float64(1), int32(1), object(1)
memory usage: 180.0+ bytes


In [46]:
df.index

RangeIndex(start=0, stop=5, step=1)

In [47]:
df.index.values

array([0, 1, 2, 3, 4], dtype=int64)

In [48]:
df.columns

Index(['id', 'year', 'sales'], dtype='object')

In [49]:
df.values # 행을 따라 

array([['A23', 2019.0, 467],
       ['C43', 2019.0, 57],
       ['A23', nan, 131],
       ['A23', 2020.0, 305],
       ['C43', 2020.0, 162]], dtype=object)

# 예제)
다음 데이터 프레임의 index, colums, values 값을 받아 새로운 데이터프레임을 만들어 주세요.

In [5]:
table_data = {'연도': [2015, 2016, 2016, 2017, 2017],
                '지사': ['한국', '한국', '미국', '한국','미국'],
                '고객 수': [200, 250, 450, 300, 500]}

df2 = pd.DataFrame(table_data)

ind = df2.index
col = df2.columns
val =  df2. values

In [12]:
pd.DataFrame(val, ind, col)

연도  지사 고객 수
0  2015  한국  200
1  2016  한국  250
2  2016  미국  450
3  2017  한국  300
4  2017  미국  500

#   

In [50]:
df.shape #(행, 열)

(5, 3)

In [51]:
len(df) #행

5

In [52]:
df.size

15

In [53]:
df.describe() # 요약 통계치 (결측치 제외)

year       sales
count     4.00000    5.000000
mean   2019.50000  224.400000
std       0.57735  162.781449
min    2019.00000   57.000000
25%    2019.00000  131.000000
50%    2019.50000  162.000000
75%    2020.00000  305.000000
max    2020.00000  467.000000

In [61]:
# 결측치 유무 판단하는 법 
df.isnull().sum().sort_values(ascending=False) # 오름차순

year     1
sales    0
id       0
dtype: int64

In [62]:
df.dtypes

id        object
year     float64
sales      int32
dtype: object

In [63]:
df.dtypes.value_counts()

float64    1
int32      1
object     1
dtype: int64

In [66]:
df.id.unique() 

array(['A23', 'C43'], dtype=object)

In [67]:
df.id.nunique()

2

#  

### 데이터 복제

In [104]:
# 딕셔너리 데이터
data_dic = {'id' : ['A23', 'C43', 'A23', 'A23', 'C43'],
            'year' : [2019, 2019, np.nan, 2020, 2020],
            'sales' : np.random.randint(0, 500, size = 5)}
data_dic
df = pd.DataFrame(data_dic)

In [105]:
df

id    year  sales
0  A23  2019.0    429
1  C43  2019.0    366
2  A23     NaN    189
3  A23  2020.0    425
4  C43  2020.0    424

In [106]:
sam_df = df
sam_df

id    year  sales
0  A23  2019.0    429
1  C43  2019.0    366
2  A23     NaN    189
3  A23  2020.0    425
4  C43  2020.0    424

In [108]:
df.iloc[2] = 0
df

id    year  sales
0  A23  2019.0    429
1  C43  2019.0    366
2    0     0.0      0
3  A23  2020.0    425
4  C43  2020.0    424

In [86]:
sam_df # ?!?!?!!!

id    year  sales
0  A23  2019.0    460
1  C43  2019.0    419
2    0     0.0      0
3  A23  2020.0    178
4  C43  2020.0      6

<참고>
### 아이디 연산자(Identity Operators)
* **is** : 양쪽 Operand가 동일한 Object를 가리키는지 아닌지를 검사합니다.
* **is not** : 양쪽 Operand가 다른 Object를 가리키는지 아닌지를 검사합니다.

동일한 객체 여부를 판별하는 연산자입니다.


id() 함수는 객체를 입력값으로 받아서 객체의 고유값(레퍼런스)을 반환하는 함수입니다.<br>
id는 파이썬이 객체를 구별하기 위해서 부여하는 일련번호입니다. 숫자로서 의미는 없습니다.<br>
id는 동일한 객체 여부를 판별할 때 사용합니다.

In [87]:
print(id(df))
print(id(sam_df))

2930064311856
2930064311856


In [88]:
df is sam_df

True

### 새로운 객체로 받기

In [14]:
data_dic = {'id' : ['A23', 'C43', 'A23', 'A23', 'C43'],
            'year' : [2019, 2019, np.nan, 2020, 2020],
            'sales' : np.random.randint(0, 500, size = 5)}
data_dic
df = pd.DataFrame(data_dic)

In [15]:
# copy 함수
df_cop = df.copy()
df_cop

id    year  sales
0  A23  2019.0    177
1  C43  2019.0    179
2  A23     NaN     54
3  A23  2020.0     77
4  C43  2020.0    453

In [16]:
df_cop.loc[2] = np.nan
df

id    year  sales
0  A23  2019.0    177
1  C43  2019.0    179
2  A23     NaN     54
3  A23  2020.0     77
4  C43  2020.0    453

In [17]:
df_cop is df

False

#  

In [18]:
# 평균
df.mean()

year     2019.5
sales     188.0
dtype: float64

In [19]:
df.mean(axis = 1) # 행 기준 : {index (0), columns (1)}

0    1098.0
1    1099.0
2      54.0
3    1048.5
4    1236.5
dtype: float64

In [138]:
# 표준편차
df.std(axis = 1)

0    1134.906384
1    1284.813021
2            NaN
3    1408.556708
4    1170.968830
dtype: float64

# 예제) 
2~100 사이의 정수를 가지는 4 x 5 의 난수 배열 G로 dataframe을 생성하고<br>
행기준 합을 구하여라.

In [23]:
np.random.seed(10)

dat = np.random.randint(2, 100, size = (4,5))
pd.DataFrame(dat).mean(axis = 1)

0    43.0
1    42.6
2    33.4
3    68.6
dtype: float64

### 특정 컬럼 제거하기

In [122]:
# head, tail
df.head() # default n = 5

id    year  sales
0  A23  2019.0    414
1  C43  2019.0    202
2  A23     NaN    289
3  A23  2020.0     28
4  C43  2020.0    364

In [124]:
df.tail()

id    year  sales
0  A23  2019.0    414
1  C43  2019.0    202
2  A23     NaN    289
3  A23  2020.0     28
4  C43  2020.0    364

In [125]:
df.tail(2)

id    year  sales
3  A23  2020.0     28
4  C43  2020.0    364

In [130]:
df[2:4] # 행 index

id    year  sales
2  A23     NaN    289
3  A23  2020.0     28

#  

In [25]:
KTX_data = {'경부선 KTX': [30000, 30000, 40000, 40000, 40000, 40000, 30000],
            '호남선 KTX': [7000, 6000, 6000, 6000, 8000, 10000, 9000],
            '경전선 KTX': [3000, 4000, 4000, 4000, 4000, 4000, 5000],
            '전라선 KTX': [300, 1000, 1000, 2000, 3000, 3000, 5000],
            '동해선 KTX': [np.nan,np.nan, np.nan, np.nan, 2000, 3000, 6000]} 
index_list = ['2011', '2012', '2013', '2014', '2015', '2016', '2017']
df_KTX = pd.DataFrame(KTX_data, index = index_list)
df_KTX

경부선 KTX  호남선 KTX  경전선 KTX  전라선 KTX  동해선 KTX
2011    30000     7000     3000      300      NaN
2012    30000     6000     4000     1000      NaN
2013    40000     6000     4000     1000      NaN
2014    40000     6000     4000     2000      NaN
2015    40000     8000     4000     3000   2000.0
2016    40000    10000     4000     3000   3000.0
2017    30000     9000     5000     5000   6000.0

In [26]:
# column 항목명으로 열 선택
df_KTX['경부선 KTX'] 

2011    30000
2012    30000
2013    40000
2014    40000
2015    40000
2016    40000
2017    30000
Name: 경부선 KTX, dtype: int64

In [27]:
df_KTX[['경부선 KTX','동해선 KTX']]

경부선 KTX  동해선 KTX
2011    30000      NaN
2012    30000      NaN
2013    40000      NaN
2014    40000      NaN
2015    40000   2000.0
2016    40000   3000.0
2017    30000   6000.0

#   

In [29]:
# index 항목 이름을 지정해 행 선택
df_KTX.loc['2017'] 

경부선 KTX    30000.0
호남선 KTX     9000.0
경전선 KTX     5000.0
전라선 KTX     5000.0
동해선 KTX     6000.0
Name: 2017, dtype: float64

In [30]:
index_list = [2011, 2012, 2013, 2014, 2015, 2016, 2017]
df_KTX2 = pd.DataFrame(KTX_data, index = index_list)
df_KTX2

경부선 KTX  호남선 KTX  경전선 KTX  전라선 KTX  동해선 KTX
2011    30000     7000     3000      300      NaN
2012    30000     6000     4000     1000      NaN
2013    40000     6000     4000     1000      NaN
2014    40000     6000     4000     2000      NaN
2015    40000     8000     4000     3000   2000.0
2016    40000    10000     4000     3000   3000.0
2017    30000     9000     5000     5000   6000.0

In [31]:
df_KTX2.loc[2017] # 본래 형에 맞춰서

경부선 KTX    30000.0
호남선 KTX     9000.0
경전선 KTX     5000.0
전라선 KTX     5000.0
동해선 KTX     6000.0
Name: 2017, dtype: float64

#   

In [33]:
df_KTX.loc['2011':'2014',['경부선 KTX','동해선 KTX']] # 행, 열 동시 지정 가능

경부선 KTX  동해선 KTX
2011    30000      NaN
2012    30000      NaN
2013    40000      NaN
2014    40000      NaN

In [152]:
df_KTX.loc[[2011,2014],['경부선 KTX','동해선 KTX']]

경부선 KTX  동해선 KTX
2011    30000      NaN
2014    40000      NaN

In [158]:
df_KTX.loc[[2011:2014],['경부선 KTX','동해선 KTX']] # 항목이름으로 연속 구간가능

SyntaxError: invalid syntax (<ipython-input-158-ec6a3f3e5849>, line 1)

In [153]:
df_KTX.loc[[0,5],['경부선 KTX','동해선 KTX']]

KeyError: "None of [Int64Index([0, 5], dtype='int64')] are in the [index]"

In [157]:
# 위치 Index를 활용해서 추출하기
df_KTX.iloc[:,[2,4]]

경전선 KTX  동해선 KTX
2011     3000      NaN
2012     4000      NaN
2013     4000      NaN
2014     4000      NaN
2015     4000   2000.0
2016     4000   3000.0
2017     5000   6000.0

#  

In [161]:
# Null값 가진 row 찾기
df_KTX.loc[df_KTX['동해선 KTX'].isnull(),:]

경부선 KTX  호남선 KTX  경전선 KTX  전라선 KTX  동해선 KTX
2011    30000     7000     3000      300      NaN
2012    30000     6000     4000     1000      NaN
2013    40000     6000     4000     1000      NaN
2014    40000     6000     4000     2000      NaN

#     

## drop

In [167]:
df_KTX3 = df_KTX.copy()

In [168]:
# 특정컬럼 삭제하기 
df_KTX3.drop('경전선 KTX',axis=1,inplace=True)
df_KTX3

경부선 KTX  호남선 KTX  전라선 KTX  동해선 KTX
2011    30000     7000      300      NaN
2012    30000     6000     1000      NaN
2013    40000     6000     1000      NaN
2014    40000     6000     2000      NaN
2015    40000     8000     3000   2000.0
2016    40000    10000     3000   3000.0
2017    30000     9000     5000   6000.0

In [ ]:
# 특정컬럼 삭제하기 
df1.drop('year',axis=1,inplace=True)

In [171]:
# 특정 인덱스를 가진 row 삭제하기 
df_KTX3.drop('2011',axis=0)
df_KTX3

경부선 KTX  호남선 KTX  전라선 KTX  동해선 KTX
2011    30000     7000      300      NaN
2012    30000     6000     1000      NaN
2013    40000     6000     1000      NaN
2014    40000     6000     2000      NaN
2015    40000     8000     3000   2000.0
2016    40000    10000     3000   3000.0
2017    30000     9000     5000   6000.0

In [162]:
# Na값이 한개라도 있는 row 삭제 
df_KTX.dropna(how='any')

경부선 KTX  호남선 KTX  경전선 KTX  전라선 KTX  동해선 KTX
2015    40000     8000     4000     3000   2000.0
2016    40000    10000     4000     3000   3000.0
2017    30000     9000     5000     5000   6000.0

In [163]:
# 모든 값이 Na인 row 삭제하기.
df_KTX.dropna(how='all')

경부선 KTX  호남선 KTX  경전선 KTX  전라선 KTX  동해선 KTX
2011    30000     7000     3000      300      NaN
2012    30000     6000     4000     1000      NaN
2013    40000     6000     4000     1000      NaN
2014    40000     6000     4000     2000      NaN
2015    40000     8000     4000     3000   2000.0
2016    40000    10000     4000     3000   3000.0
2017    30000     9000     5000     5000   6000.0

#  

# Boolean Indexing
Boolean이란 True False로 이루어진 값들을 의미한다. 이들을 바탕으로 특정 조건을 만족하는 column이나 row를 추출할 수 있다.

In [241]:
# 딕셔너리 데이터
data_dic = {'id' : ['A23', 'C43', 'A23', 'A23', 'C43'],
            'year' : [2019, 2019, np.nan, 2020, 2020],
            'sales' : np.random.randint(0, 500, size = 5)}
data_dic
df = pd.DataFrame(data_dic)

In [243]:
df[df.year == 2019]

id    year  sales
0  A23  2019.0    203
1  C43  2019.0    284

In [245]:
df.query("id == 'A23'")

id    year  sales
0  A23  2019.0    203
2  A23     NaN    289
3  A23  2020.0    468

In [250]:
df.groupby('id')['sales'].sum().reset_index()

id  sales
0  A23    960
1  C43    534

#   

In [35]:
# csv파일 읽어오기
# 현재의 Working Directory에 읽어오고자 하는 파일을 넣고 pd.read_csv('파일이름.csv',engine='python',encoding='') 
# encoding은 자료에 맞춰서 진행 
# 현재 Working Directory에 존재하지 않는다면 파일 경로와 함께 pd.read_csv('파일경로.csv',engine='python',encoding='')
dat = pd.read_csv('cali.csv',engine='python',encoding='cp949')
dat = dat.iloc[np.random.randint(len(dat), size = (12,))]

In [36]:
dat

Unnamed: 0  longitude  latitude  housing_median_age  total_rooms  \
14001       14001    -117.29     34.57                22.0       1054.0   
16051       16051    -122.48     37.76                52.0       2684.0   
11318       11318    -117.99     33.77                15.0       2081.0   
15813       15813    -122.42     37.76                52.0       4407.0   
12301       12301    -116.87     33.91                37.0       1858.0   
6899         6899    -118.13     34.04                40.0       1444.0   
16793       16793    -122.46     37.66                36.0       2535.0   
17790       17790    -121.82     37.37                41.0       1558.0   
17037       17037    -122.25     37.49                43.0       2607.0   
3932         3932    -118.59     34.20                18.0        847.0   
1366         1366    -122.13     38.01                48.0       2123.0   
8281         8281    -118.15     33.78                35.0       2768.0   

       total_bedrooms  population  households  median_income  \
14001           239.0       428.0       239.0         1.2548   
16051           574.0      1395.0       549.0         3.9097   
11318           531.0      1617.0       561.0         3.4955   
15813          1192.0      2280.0      1076.0         3.3937   
12301           361.0      1632.0       310.0         2.7536   
6899            312.0       881.0       303.0         3.1083   
16793           451.0      1390.0       436.0         5.3398   
17790           281.0       970.0       304.0         4.4167   
17037           477.0      1225.0       461.0         4.2240   
3932            185.0       733.0       178.0         5.2149   
1366            494.0       859.0       474.0         1.8523   
8281            752.0      1277.0       651.0         3.6193   

       median_house_value ocean_proximity  
14001             68300.0          INLAND  
16051            323800.0        NEAR BAY  
11318            160900.0       <1H OCEAN  
15813            270000.0        NEAR BAY  
12301             73100.0          INLAND  
6899             220500.0       <1H OCEAN  
16793            260900.0      NEAR OCEAN  
17790            215200.0       <1H OCEAN  
17037            349600.0      NEAR OCEAN  
3932             201900.0       <1H OCEAN  
1366             144800.0        NEAR BAY  
8281             250000.0      NEAR OCEAN

#### 예제 )
불러온 데이터에 불필요한 열이 존재합니다. 해당 열을 제거 해 주세요.

In [37]:
dat.columns

Index(['Unnamed: 0', 'longitude', 'latitude', 'housing_median_age',
       'total_rooms', 'total_bedrooms', 'population', 'households',
       'median_income', 'median_house_value', 'ocean_proximity'],
      dtype='object')

In [39]:
dat.drop('Unnamed: 0', axis = 1)

longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
14001    -117.29     34.57                22.0       1054.0           239.0   
16051    -122.48     37.76                52.0       2684.0           574.0   
11318    -117.99     33.77                15.0       2081.0           531.0   
15813    -122.42     37.76                52.0       4407.0          1192.0   
12301    -116.87     33.91                37.0       1858.0           361.0   
6899     -118.13     34.04                40.0       1444.0           312.0   
16793    -122.46     37.66                36.0       2535.0           451.0   
17790    -121.82     37.37                41.0       1558.0           281.0   
17037    -122.25     37.49                43.0       2607.0           477.0   
3932     -118.59     34.20                18.0        847.0           185.0   
1366     -122.13     38.01                48.0       2123.0           494.0   
8281     -118.15     33.78                35.0       2768.0           752.0   

       population  households  median_income  median_house_value  \
14001       428.0       239.0         1.2548             68300.0   
16051      1395.0       549.0         3.9097            323800.0   
11318      1617.0       561.0         3.4955            160900.0   
15813      2280.0      1076.0         3.3937            270000.0   
12301      1632.0       310.0         2.7536             73100.0   
6899        881.0       303.0         3.1083            220500.0   
16793      1390.0       436.0         5.3398            260900.0   
17790       970.0       304.0         4.4167            215200.0   
17037      1225.0       461.0         4.2240            349600.0   
3932        733.0       178.0         5.2149            201900.0   
1366        859.0       474.0         1.8523            144800.0   
8281       1277.0       651.0         3.6193            250000.0   

      ocean_proximity  
14001          INLAND  
16051        NEAR BAY  
11318       <1H OCEAN  
15813        NEAR BAY  
12301          INLAND  
6899        <1H OCEAN  
16793      NEAR OCEAN  
17790       <1H OCEAN  
17037      NEAR OCEAN  
3932        <1H OCEAN  
1366         NEAR BAY  
8281       NEAR OCEAN

#### 예제 )
해당 데이터의 housing_median_age, total_rooms, total_bedrooms, population, households, median_income, median_house_value 열의 평균값을 구해주세요

In [40]:
dat.iloc[:, 2:-1].mean()

latitude                  35.860000
housing_median_age        36.583333
total_rooms             2163.833333
total_bedrooms           487.416667
population              1223.916667
households               461.833333
median_income              3.548550
median_house_value    211583.333333
dtype: float64

#### 예제) 
Ocean_proximity에 따른 median_income와 median_house_value의 각 평균을 구해주세요,

In [41]:
dat.groupby('ocean_proximity')["median_income","median_house_value"].mean()

median_income  median_house_value
ocean_proximity                                   
<1H OCEAN             4.058850       199625.000000
INLAND                2.004200        70700.000000
NEAR BAY              3.051900       246200.000000
NEAR OCEAN            4.394367       286833.333333